### PR TITLE
fix(github): ignore recipe if not selected, fix #76

### LINKED ISSUE #76: Ignores "create github repository"
> Do you want to use create the github repository? (platanus/tracker): No
...
> Initialized empty Git repository in /Users/gmq/Documents/Trabajo/platanus/tracker/.git/
    ...
       force  bin/setup
         run  chmod a+x bin/setup from "."
         run  hub create  platanus/tracker from "."
Updating origin
created repository: platanus/tracker

```
$ potassium -v
potassium version 2.0.0
```

### PR DESCRIPTION
**Pull request by gmq**

### CODE REVIEW

File: lib/potassium/recipes/github.rb [hunk 1]
```diff
@@ -15,7 +15,7 @@ def ask
   end
 
   def create
-    github_repo_create(get(:github_repo_name), get(:github_repo_private))
+    github_repo_create(get(:github_repo_name), get(:github_repo_private)) if selected?(:github_repo_create)
```
Comment (monkeyci) [inline lib/potassium/recipes/github.rb]: Line is too long. [107/100]

Comment (blackjid) [inline lib/potassium/recipes/github.rb]: buena memo!, podriamos complacer al mono por favor?? con un bello rebase-push-force?
